version: "3.8"

services:
  ipscan:
    image: ghcr.io/ldpc520/ipscan:latest       # 远程镜像（从GHCR拉取）
    build: .                                     # 本地构建备选
    container_name: ipscan
    restart: unless-stopped
    ports:
      - "6603:6603"
    environment:
      # - REMOTE_TOKEN_URL=https://nav.sdyun.eu.org/token/ip_token.txt  # 可选，代码已有默认值
      - CONFIG_PASSWORD=admin                      # 面板密码
      - ENABLE_SCANNER=1
      - SCAN_INTERVAL=900
    volumes:
      - ./data:/app/data
      - ./config.ini:/app/config.ini
      - ./组播ID:/app/组播ID
